In [1]:
import numpy as np

In [2]:
list = [1, 2, 3]

In [3]:
np.array(list)

array([1, 2, 3])

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
list_2d = [[1, 2, 4], [3, 5, 7], [6, 8, 10]]

In [6]:
np.array(list_2d)

array([[ 1,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [7]:
array_1 = np.arange(0, 100000, 2000)

In [8]:
array_1.size

50

In [9]:
array_1.resize(10, 5)

In [10]:
array_1

array([[    0,  2000,  4000,  6000,  8000],
       [10000, 12000, 14000, 16000, 18000],
       [20000, 22000, 24000, 26000, 28000],
       [30000, 32000, 34000, 36000, 38000],
       [40000, 42000, 44000, 46000, 48000],
       [50000, 52000, 54000, 56000, 58000],
       [60000, 62000, 64000, 66000, 68000],
       [70000, 72000, 74000, 76000, 78000],
       [80000, 82000, 84000, 86000, 88000],
       [90000, 92000, 94000, 96000, 98000]])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((10, 11))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones((10, 10))*2

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [14]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(10)*12

array([[12.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 12.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 12.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 12.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 12.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 12.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 12.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 12.]])

In [16]:
np.random.rand(5, 5, 4)

array([[[0.5605584 , 0.11114547, 0.90019509, 0.06258929],
        [0.70155885, 0.27694362, 0.19446846, 0.40686092],
        [0.68333785, 0.03858134, 0.78322585, 0.85214351],
        [0.57530037, 0.9661533 , 0.07093287, 0.36001238],
        [0.06040733, 0.65456796, 0.61686924, 0.34779926]],

       [[0.12138524, 0.94639981, 0.26349785, 0.79166325],
        [0.45412618, 0.83749932, 0.41125058, 0.85226588],
        [0.2061301 , 0.31133982, 0.29475623, 0.99762493],
        [0.58240411, 0.32805383, 0.5506298 , 0.91658688],
        [0.8583209 , 0.89284012, 0.46489961, 0.42966368]],

       [[0.38133499, 0.13537594, 0.76739574, 0.4318699 ],
        [0.5863513 , 0.32065941, 0.4517998 , 0.42286799],
        [0.97716923, 0.47459265, 0.72672055, 0.4365226 ],
        [0.78680644, 0.59362052, 0.17761114, 0.89381451],
        [0.8026777 , 0.58796469, 0.15617622, 0.33717593]],

       [[0.52774713, 0.01488648, 0.30377888, 0.83974459],
        [0.54675198, 0.67762482, 0.14785057, 0.33797667],
        

In [17]:
np.random.randn(12, 12)
#gaussian distribution, centered around 0

array([[ 1.76991926, -1.48850291,  0.77864539,  0.85179695, -0.08189259,
         0.02196509,  1.99350373, -0.1673022 , -0.27126149,  1.09721987,
        -0.71184253, -0.01846402],
       [-0.41313059,  1.07429298, -1.17472169,  0.82071439,  0.89062333,
        -0.93287464,  0.35741637,  0.13207423,  0.96266345,  1.53137381,
         2.51093405,  0.79691654],
       [-0.25650628,  0.53981236,  0.51104785,  1.69487181,  0.2689382 ,
         0.18289004,  0.17544977,  1.53290207, -0.25940991, -0.78044137,
         0.5749802 ,  0.1364597 ],
       [ 0.82746293,  0.0161632 ,  0.82967746,  0.58423832, -0.2394007 ,
         0.03943294, -0.35369221,  0.43465001, -0.23664648,  0.27425821,
        -1.03647641,  0.71270969],
       [ 1.61215025, -0.29513774, -1.32229376,  0.94302896, -2.01364979,
         0.05346138, -2.31027904,  0.5060893 , -2.23852999,  0.30980076,
        -1.18750158, -0.43303899],
       [ 1.31133143,  1.05042951, -1.57004305, -1.66200513, -0.77330297,
        -1.19711687,  

In [18]:
np.random.randint(0, 10, (2, 3), dtype = int)

array([[9, 5, 7],
       [0, 6, 4]])

In [19]:
rand_int_array = np.random.randint(0, 50, 10)
rand_int_array

array([ 7, 31, 31,  4, 10,  1,  0, 28, 41, 23])

In [20]:
rand_int_array.max()


41

In [21]:
rand_int_array.min()

0

In [22]:
rand_int_array.argmax()

8

In [23]:
rand_int_array.argmin()

6

In [24]:
rand_int_array.dtype

dtype('int32')

In [25]:
import numpy.random as rand

In [26]:
rand.randint(1, 10, 10)

array([7, 6, 6, 5, 6, 8, 2, 4, 5, 6])

In [27]:
sample_array_1D = np.arange(100)

In [28]:
sample_array_2D = np.arange(0, 100).reshape(10, 10)

In [29]:
sample_array_1D[0:13]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
sample_array_2D[0:10, 0:2]

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41],
       [50, 51],
       [60, 61],
       [70, 71],
       [80, 81],
       [90, 91]])

In [31]:
sample_array_1D_slice = sample_array_1D[0:10]

In [32]:
sample_array_1D_slice[:] = 93

In [33]:
sample_array_1D_slice

array([93, 93, 93, 93, 93, 93, 93, 93, 93, 93])

In [34]:
sample_array_1D

array([93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Numpy do not create a copy, it creates a new refrence

In [35]:
sample_array_1D_copy = sample_array_1D.copy()[0:10]

In [36]:
sample_array_1D_copy[:] = 9999

In [37]:
sample_array_1D_copy

array([9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999])

In [38]:
sample_array_1D

array([93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

UCHANGED

In [39]:
print(sample_array_2D[0, 9])
#Single bracket method
print(sample_array_2D[0][9])

9
9


In [40]:
sample_array_2D[0:3, 0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [48]:
arr_2d = np.arange(5, 50, 5).reshape(3, 3)

In [51]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
arr_2d[1:, :]

array([[20, 25, 30],
       [35, 40, 45]])

Conditional Selection

In [53]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
bool_array = arr == 6

In [56]:
bool_array

array([False, False, False, False, False,  True, False, False, False,
       False])

In [57]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [58]:
arr[arr < 3]

array([1, 2])

In [60]:
array_2d = np.arange(50).reshape(5, 10)
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [63]:
array_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

Array Operations

In [65]:
arr = np.arange(0,11)

In [66]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [67]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [68]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [69]:
arr / arr

C:\Users\Richter\AppData\Local\Temp/ipykernel_19568/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

NaN

In [71]:
arr ** arr

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

In [72]:
np.sqrt(arr**arr)

array([1.00000000e+00, 1.00000000e+00, 2.00000000e+00, 5.19615242e+00,
       1.60000000e+01, 5.59016994e+01, 2.16000000e+02, 9.07492700e+02,
       4.09600000e+03, 1.96830000e+04, 3.75508376e+04])

In [74]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [75]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [81]:
arr = np.arange(0, 365, 5)

In [79]:
np.sin(arr)

array([ 0.00000000e+00, -9.58924275e-01, -5.44021111e-01,  6.50287840e-01,
        9.12945251e-01, -1.32351750e-01, -9.88031624e-01, -4.28182669e-01,
        7.45113160e-01,  8.50903525e-01, -2.62374854e-01, -9.99755173e-01,
       -3.04810621e-01,  8.26828679e-01,  7.73890682e-01, -3.87781635e-01,
       -9.93888654e-01, -1.76075620e-01,  8.93996664e-01,  6.83261715e-01,
       -5.06365641e-01, -9.70535284e-01, -4.42426781e-02,  9.45435334e-01,
        5.80611184e-01, -6.16040459e-01, -9.30105950e-01,  8.83686861e-02,
        9.80239659e-01,  4.67745162e-01, -7.14876430e-01, -8.73311983e-01,
        2.19425258e-01,  9.97797279e-01,  3.46649455e-01, -8.01134595e-01,
       -8.01152636e-01,  3.46621180e-01,  9.97799279e-01,  2.19454668e-01,
       -8.73297297e-01, -7.14897508e-01,  4.67718518e-01,  9.80245622e-01,
        8.83987125e-02, -9.30094878e-01, -6.16064204e-01,  5.80586641e-01,
        9.45445155e-01, -4.42125632e-02, -9.70528020e-01, -5.06391635e-01,
        6.83239704e-01,  